# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# sum of even fibs
sum = 2

fib_list = [1, 2]

while fib_list[-1] < 4000000:

    #add last two fibs and append it to the list
    fib_list.append(fib_list[-1] + fib_list[-2])

    # check if the last number is even
    if fib_list[-1] % 2 == 0:
        sum += fib_list[-1]

print('last fib', fib_list[-1], 'sum', sum)